# Enterprise Build and SonarQube Pipeline with Docker Build

name: Enterprise Build and SonarQube Pipeline

on:
  workflow_dispatch:

jobs:

  build-and-scan:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Verify Java Installation
        run: |
          java -version
          mvn -version

      - name: Build, Test and SonarQube Analysis
        run: |
          mvn clean verify \
            org.sonarsource.scanner.maven:sonar-maven-plugin:4.0.0.4121:sonar \
            -Dsonar.projectKey=enterprise-java-pipeline \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }}

      - name: Verify Generated Files
        run: |
          ls -R target

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-build-artifact
          path: target/*.jar

  docker-build:

    needs: build-and-scan

    runs-on: ubuntu-latest

    steps:

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: java-build-artifact
          path: target

      - name: Verify Downloaded Artifact
        run: |
          echo "Downloaded Files:"
          ls -R target

      - name: Generate Image Version
        run: |
          echo "IMAGE_VERSION=${{ github.run_number }}" >> $GITHUB_ENV
          echo "Version = ${{ github.run_number }}"

      - name: Build Docker Image
        run: |
          docker build \
            -t ${{ secrets.DOCKER_USERNAME }}/enterprise-java-pipeline:${{ github.run_number }} \
            -t ${{ secrets.DOCKER_USERNAME }}/enterprise-java-pipeline:latest .
      - name: Verify Repository Files
        run: |
          echo "Current Directory:"
          pwd

          echo ""
          echo "Files:"
          ls -la

          echo ""
          echo "Searching for Dockerfile:"
          find . -name Dockerfile     
         
      - name: Verify Docker Images
        run: |
          docker images

      - name: Inspect Docker Image
        run: |
          docker image inspect \
          ${{ secrets.DOCKER_USERNAME }}/enterprise-java-pipeline:${{ github.run_number }}
